name: Install Poetry

on:
  push:
    branches:
      - main

jobs:
  install-poetry:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install Poetry
        uses: poetry/install-poetry@v1
        with:
          python-version: 3.x

      - name: Set up Python and Poetry
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Setup Poetry
        run: |
          poetry install

      - name: Run tests
        run: |
          poetry run pytest

      - name: Build and publish
        run: |
          poetry build
          poetry publish
