name: GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Poetry and set up Python dependencies
        run: |
          uses: actions/setup-python@v2
          with:
            virtualenv-version: system
            python-version: 3.9
      - name: Install Poetry and set up Python
        uses: 'poetry/install-poetry@v1'
- name: Install Poetry
        run: |\n          poetry run
          poetry --version
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
          run: |
            poetry run isort . --check --diff
          uses: actions/setup-python@v2
          with:
            python-version: 3.x
- name: Install Poetry
        uses: 'poetry/install-poetry@v1'
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      - name: Add Poetry to PATH
        run: |
          poetry run isort . --check --diff

      - name: Set up Python and Poetry
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Setup Poetry

      - name: Setup Poetry
        uses: 'actions/setup-poetry@v2'
        with:
          python-version: 3.x

      # Add other steps as needed
