name: GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
          with:
            python-version: 3.x
        with:
          python-version: 3.x

      - name: Install poetry
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
          cache: 'pip'
      - name: Run isort with Poetry
        run: poetry run isort . --check --diff
        

      - name: Run isort with Poetry
    run: poetry run isort . --check --diff
