name: GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Poetry
        uses: run: poetry run isort . --check --diff
          with:
            poetry-version: 'latest'
          python-version: '3.x'
          python-version: 3.x
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      # Add other steps as needed
