name: GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Poetry dependencies
        run: |
          uses: actions/setup-python@v2
          with:
            python-version: 3.x
          uses: actions/setup-python@v2
          with:
            python-version: 3.x
- name: Install Poetry
        uses: 'poetry/install-poetry@v1'
        uses: 'poetry/install-poetry@v1'
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
        if: runner.os == 'Linux' || runner.os == 'Mac OS' || runner.os == 'Windows'
      - name: Add Poetry to PATH
        run: |
          poetry run isort . --check --diff

      - name: Set up Poetry
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Setup Poetry

      - name: Set up Poetry
        uses: 'actions/setup-poetry@v2'
        uses: 'actions/setup-poetry@v2'
        with:
          python-version: 3.x

            - uses: actions/setup-python@v2
        with:
          python-version: 3.9
