name: GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
          with:
            python-version: 3.x
        with:
          python-version: 3.x

      - name: Install Poetry
        uses: actions/install-poetry@v1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install Poetry
        uses: actions/install-poetry@v1
        run: ${{ env.PATH }}:/home/runner/.poetry/bin poetry run isort . --check --diff

      - name: Run isort with Poetry
        run: ~/.poetry/bin/poetry run isort . --check --diff
